"""Pydantic schemas for Node 5 (Synthesis) output."""

from typing import Any, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Reusable UI building-blocks (moved from api/schemas/query.py)
# ---------------------------------------------------------------------------

class RecommendationCard(BaseModel):
    category: str
    model_name: str
    reason: str


class Citation(BaseModel):
    id: str
    label: str
    url: str


class Warning(BaseModel):
    code: str
    message: str


# ---------------------------------------------------------------------------
# Tier table building-blocks (3 tier tables replace single ComparisonTable)
# ---------------------------------------------------------------------------

class TierBenchmarkScore(BaseModel):
    """A single benchmark score cell in a tier table."""
    value: Optional[float] = None
    is_estimated: bool = False
    estimation_source: Optional[str] = None  # e.g. "MMLU (5-shot)"


class TierTableRow(BaseModel):
    model_name: str
    provider: str
    speed: str          # e.g. "fast (142)" or "medium"
    score: float        # tier-specific blended_score (0-1)
    benchmark_scores: List[TierBenchmarkScore] = []


class TierTable(BaseModel):
    tier_name: str      # "Top Performance", "Balanced", "Budget Picks"
    columns: List[str]  # benchmark column display names
    rows: List[TierTableRow] = []


class BenchmarkUsed(BaseModel):
    """Entry in the 'Benchmarks Used' reference table."""
    benchmark_name: str  # name_normalized (variant) if variant exists
    weight: float        # relevance_weight from judgment
    description: str


# ---------------------------------------------------------------------------
# LLM structured output (natural-language parts only)
# ---------------------------------------------------------------------------

class RecommendationReasons(BaseModel):
    """Per-category recommendation reasons generated by the LLM."""

    top_performance: Optional[str] = Field(
        None,
        description="Why this model wins for top performance, referencing benchmarks.",
    )
    balanced: Optional[str] = Field(
        None,
        description="Why this model wins for balanced use, referencing benchmarks.",
    )
    budget: Optional[str] = Field(
        None,
        description="Why this model wins for budget use, referencing benchmarks.",
    )


class SynthesisLLMOutput(BaseModel):
    """LLM structured output for Node 5.

    The LLM generates ONLY natural-language parts; deterministic components
    are built by the node function.
    """

    task_summary: str = Field(
        description="1-2 sentence rephrasing of the user's intended task."
    )
    recommendation_reasons: RecommendationReasons = Field(
        description=(
            "One reason per category explaining why the model wins, referencing benchmarks. "
            "Only include categories that have at least one model."
        )
    )
    offset_calibration_note: Optional[str] = Field(
        None,
        description=(
            "If any is_estimated=true scores exist, note which models/benchmarks "
            "were estimated and why. Null otherwise."
        ),
    )


# ---------------------------------------------------------------------------
# Full synthesis output stored in AgentState
# ---------------------------------------------------------------------------

class SynthesisOutput(BaseModel):
    """Complete synthesis output. Combines LLM text with deterministic components."""

    llm_output: Optional[SynthesisLLMOutput] = None
    summary_markdown: str
    tier_tables: List[TierTable] = []
    recommendation_cards: List[RecommendationCard] = []
    benchmarks_used: List[BenchmarkUsed] = []
    citations: List[Citation] = []
    warnings: List[Warning] = []
